{
 "title": "Postgres Exporter ",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "db",
    "query": {
     "query": "label_values(pg_stat_database_blks_read, datname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connections by DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (datname,state) (pg_stat_activity_count{datname=~\"$db\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TPS (commit + rollback)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (datname) (\n  rate(pg_stat_database_xact_commit{datname=~\"$db\"}[1m]) +\n  rate(pg_stat_database_xact_rollback{datname=~\"$db\"}[1m])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block reads/sec1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_stat_database_blks_read{datname=~\"$db\"}[5m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache hits/sec",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_stat_database_blks_hit{datname=~\"$db\"}[5m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_stat_database_blks_hit{datname=~\"$db\"}[1m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sum by (datname) (pg_stat_database_blks_read)",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (datname) (pg_stat_database_blks_read{datname=~\"$db\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block reads/sec ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_stat_database_blks_read{datname=~\"$db\"}[1m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TPS (commit + rollback per sec)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by (datname) (\n  rate(pg_stat_database_xact_commit[5m]) +\n  rate(pg_stat_database_xact_rollback[5m])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TPS last 1h",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by (datname) (\n  increase(pg_stat_database_xact_commit{datname=~\"$db\"}[1h]) +\n  increase(pg_stat_database_xact_rollback{datname=~\"$db\"}[1h])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime (seconds)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (datname) (\n  rate(pg_stat_database_xact_commit{datname=~\"$db\"}[5m]) +\n  rate(pg_stat_database_xact_rollback{datname=~\"$db\"}[5m])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TPS 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by (datname) (\n  rate(pg_stat_database_xact_commit{datname=~\"$db\"}[1m]) +\n  rate(pg_stat_database_xact_rollback{datname=~\"$db\"}[1m])\n)\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active vs idle",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum by (state) (pg_stat_activity_count{datname=~\"$db\"})\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}