{
 "title": "Weather & External API Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "city",
    "label": "city",
    "query": {
     "query": "label_values(weather_temperature_celsius, city)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Humidity (%)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "weather_temperature_celsius{city=\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Temperature (°C)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_temperature_celsius{city=\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature vs Feels Like",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "weather_temp_difference{city=\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Feels Like (°C)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_feels_like_celsius{city=\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sunrise Time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_sunrise_unix{city=\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sunset Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_sunset_unix{city=\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Visibility (m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "weather_visibility_m{city=\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pressure (hPa)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "weather_pressure_hpa{city=\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cloud Coverage (%)",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "weather_clouds_percent{city=\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wind Speed (m/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "weather_wind_speed_mps{city=\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}